### PR TITLE
feat: use synckit worker to gain performance

### LINKED ISSUE #4: [Performance] the cost invoke CLI every time is high
## Problem
Because of [blade-formatter](https://github.com/shufo/blade-formatter) using in coc-blade reads vscode-oniguruma's WASM on startup, CLI needs read WASM binary every time.

WASM size is about 500kb but its I/O / Initialization process impacts formatting performance so the cost invoke CLI every time is high.

## Solution
- Use worker thread for formatting.

Once worker loads WASM binary, it keeps WASM on memory until vim finished. 

### worker version example:

https://user-images.githubusercontent.com/1641039/151662682-ad929b2b-9828-4d52-8bfc-b7f3c0b97788.mp4

Once WASM cache load into memory, it will gain about 10x ~ 20x times faster throughput than CLI

### PR DESCRIPTION
**Pull request by shufo**
## Context
-  closes: #4 

## Problem
- see #4 

## Solution
- Use synckit worker and synchronously format inside it instead of spawn child process

### CODE REVIEW

**Comment by shufo** [comment]
I think mostly works fine but if syntax error occurs, it results below behaviour.

https://user-images.githubusercontent.com/1641039/151663344-a10213fa-08e0-4e99-80a5-c6f534eaddb2.mp4

This behaviour is using coc.nvim's format on save.

```json
~~
  4   "coc.preferences.formatOnSaveFiletypes": [
  2     "blade",
  8   ],

```

and syntax error on `:call CocAction('format')` results vim process hang up.

https://user-images.githubusercontent.com/1641039/151663982-6b9a3eb7-56ca-4193-b5e5-3a268edd5f03.mp4

I'm not familiar with coc.nvim extension system, so if you know anything about this behavior, I'd appreciate it!

**Comment by shufo** [comment]
I forgot to reject error in catch 
Now It's work as expected I think.

https://user-images.githubusercontent.com/1641039/151711934-821fa671-af05-4a92-80d8-bc30d9bf26ca.mp4

**Comment by yaegassy** [comment]
Hi, @shufo. Sorry for the late reply. Thanks for checking out "coc-blade".

The other day, blade-formatter was replaced by typescript from javascript, so I was thinking of refactoring in `api` instead of `cli` in coc-blade's blade-formatter.

Pull Request, Thank you very much. I'll check it out later.

**Comment by yaegassy** [comment]
@shufo I got to try PR! I am very surprised that it is running very fast.

I've never used `worker` or `synckit` before, so I'm a little nervous about maintaining them in the future, but if they're this fast, no problem.

In coc-blade, the files under src are excluded by `.npmignore`, so I will make some adjustments after the merge.

**Comment by shufo** [comment]
@yaegassy 
Thank you!

**Pull request merged**
